export const INTERESTS = [
  "Música",
  "Cine",
  "Deportes",
  "Viajes",
  "Gastronomía",
  "Arte",
  "Literatura",
  "Tecnología",
  "Fotografía",
  "Baile",
  "Yoga",
  "Meditación",
  "Cocina",
  "Jardinería",
  "Mascotas",
  "Voluntariado",
  "Idiomas",
  "Teatro",
  "Moda",
  "Fitness",
];

export const DEPARTMENTS = {
  Amazonas: ["Leticia", "Puerto Nariño"],
  Antioquia: ["Medellín", "Bello", "Envigado", "Itagüí", "Sabaneta"],
  Arauca: ["Arauca", "Saravena"],
  Atlántico: ["Barranquilla", "Soledad", "Malambo", "Puerto Colombia"],
  Bolívar: ["Cartagena", "Magangué", "Turbaco"],
  Boyacá: ["Tunja", "Duitama", "Sogamoso"],
  Caldas: ["Manizales", "La Dorada", "Chinchiná"],
  Caquetá: ["Florencia", "San Vicente del Caguán"],
  Casanare: ["Yopal", "Aguazul"],
  Cauca: ["Popayán", "Santander de Quilichao"],
  Cesar: ["Valledupar", "Aguachica"],
  Chocó: ["Quibdó", "Istmina"],
  Córdoba: ["Montería", "Cereté", "Lorica"],
  Cundinamarca: ["Bogotá", "Soacha", "Girardot", "Facatativá", "Zipaquirá"],
  Guainía: ["Inírida"],
  Guaviare: ["San José del Guaviare"],
  Huila: ["Neiva", "Pitalito", "Garzón"],
  "La Guajira": ["Riohacha", "Maicao", "Uribia"],
  Magdalena: ["Santa Marta", "Ciénaga", "Fundación"],
  Meta: ["Villavicencio", "Acacías", "Granada"],
  Nariño: ["Pasto", "Tumaco", "Ipiales"],
  "Norte de Santander": ["Cúcuta", "Ocaña", "Pamplona"],
  Putumayo: ["Mocoa", "Puerto Asís"],
  Quindío: ["Armenia", "Calarcá", "La Tebaida"],
  Risaralda: ["Pereira", "Dosquebradas", "Santa Rosa de Cabal"],
  "San Andrés y Providencia": ["San Andrés", "Providencia"],
  Santander: ["Bucaramanga", "Floridablanca", "Girón", "Piedecuesta"],
  Sucre: ["Sincelejo", "Corozal", "Tolú"],
  Tolima: ["Ibagué", "Espinal", "Honda"],
  "Valle del Cauca": ["Cali", "Buenaventura", "Palmira", "Tuluá", "Buga"],
  Vaupés: ["Mitú"],
  Vichada: ["Puerto Carreño"],
};

export const GENDERS = ["male", "female", "other", "any"];
